[package]
name = "gfaffix"
version = "0.1.2"
authors = ["Daniel Doerr <daniel.doerr@hhu.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap        = "3.0.0-beta.2"
rustc-hash = "1"
regex = "1"
# rs-handlegraph has a critical bug that causes some edges to be ignored. This
# is fixed in the repsitory, but not yet in a release. Until that happens, use
# the version from the repository (https://github.com/chfi/rs-handlegraph.git)
handlegraph = { path = "../rs-handlegraph/" }
#handlegraph = "0.7.0-alpha.7"
gfa         = "0.10"
quick-csv  = "0.1.6"

# Logging and error management
log        = "0.4"
env_logger = "0.7"
