[package]
name = "gfaffix"
version = "0.1.0"
authors = ["Daniel Doerr <daniel.doerr@hhu.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bstr       = "0.2" 
clap        = "3.0.0-beta.2"
rustc-hash = "1"
handlegraph = "0.7.0-alpha.7"
gfa         = "0.10"
quick-csv  = "0.1.6"

# Logging and error management
log        = "0.4"
anyhow     = "1"
thiserror  = "1"
env_logger = "0.7"
