[package]
name = "gfaffix"
version = "0.1.3"
authors = ["Daniel Doerr <daniel.doerr@hhu.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap        = {version = "3.1.6", features = [ "derive" ] }
rustc-hash = "1"
regex = "1"
handlegraph = "0.7.0-alpha.9"
gfa         = "0.10"
quick-csv  = "0.1.6"

# Logging and error management
log        = "0.4"
env_logger = "0.7"
